# Generated by Django 5.1.4 on 2024-12-12 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientlogs',
            options={'verbose_name': 'Пользовательский лог', 'verbose_name_plural': 'Пользовательские логи'},
        ),
    ]
